---
common_hostname: "{{ ansible_facts['ansible_eth0']['ipv4']['address'] | replace('.', '-') }}"

common_packages_base:
  - "ca-certificates"
  - "gnupg"
  - "net-tools"
  - "lsb-release"
  - "ufw"
  - "tmux"
  - "git"
  - "curl"
  - "vim"
  - "unzip"
  - "make"
  # - "fail2ban"
  # - "lynis"

common_packages_ubuntu:
  - "unattended-upgrades"
  - "htop"

common_services_disabled:
  - bluetooth
  - modemmanager
  - cups
  - cups-browsed
  - apport
  - whoopsie
  - lxd
  - lxcfs
  - rpcbind
  - avahi-daemon
  - avahi-dnsconfd

common_sysctl_config:
  # disable IPv6
  # "net.ipv6.conf.all.disable_ipv6": "1"
  # "net.ipv6.conf.lo.disable_ipv6": "1"
  # "net.ipv6.conf.default.disable_ipv6": "1"

# SWAP
common_swapfile_size: "{{ ((ansible_memtotal_mb | int / 2) if (ansible_memtotal_mb | int >= 2048) else '2048') }}"
common_swapfile_path: "/swap.img"
common_swap_sysctl_config:
  "vm.swappiness": "25"
  "vm.vfs_cache_pressure": "100"

# Datetime
common_timezone: "Europe/Warsaw"

# SSH
common_ssh_port: "{{ vault_ssh_port }}"
common_ssh_knock_seq: "{{ vault_ssh_knock_seq | map('string') | join(',') }}"
common_whitelist_ips: "{{ vault_whitelist_ips }}"

# Users
common_new_users: "{{ vault_new_users }}"
common_remove_users: "{{ vault_remove_users }}"
