---
- name: Restart SSH service
  ansible.builtin.systemd_service:
    name: "ssh"
    state: restarted
    daemon_reload: true

- name: Restart knockd service
  ansible.builtin.systemd_service:
    name: "knockd"
    state: restarted

- name: Restart systemd
  ansible.builtin.systemd:
    daemon_reexec: true

- name: Restart UFW service
  ansible.builtin.systemd_service:
    name: "ufw"
    state: restarted

- name: Reload UFW rules
  community.general.ufw:
    state: reloaded
