- name: Full-upgrade system
  ansible.builtin.apt:
    upgrade: full
    autoremove: true
    update_cache: true
    force_apt_get: true
    cache_valid_time: 86400
  notify:
    - Reboot
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install packages
  ansible.builtin.package:
    name: "{{ common_packages_base }}"
    state: present

- name: Install ubuntu-specific packages
  ansible.builtin.apt:
    name: "{{ common_packages_ubuntu }}"
    state: present
    cache_valid_time: 86400
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Ensure unattended-upgrades service is enabled and running
  ansible.builtin.systemd:
    name: unattended-upgrades
    enabled: true
    state: started
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
