- name: Setting new hostname - {{ new_hostname }}
  ansible.builtin.hostname:
    name: "{{ new_hostname }}"
  vars:
    raw_ip: "{{ ansible_default_ipv4.address }}"
    new_hostname: "{{ raw_ip | replace('.', '-') }}"

- name: Setup timezone - {{ common_timezone }}
  community.general.timezone:
    name: "{{ common_timezone }}"

- name: Enable NTP (Network Time Protocol)
  ansible.builtin.systemd:
    name: systemd-timesyncd
    enabled: true
    state: started

- name: Configure hosts file
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 {{ ansible_hostname }}"
    state: present

- name: Adjust sysctl.conf
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: "present"
    reload: true
  with_dict: "{{ common_sysctl_config }}"

- name: Disable root password
  ansible.builtin.user:
    name: root
    password_lock: true

- name: Copy weekly reboot script to the server
  ansible.builtin.copy:
    src: "{{ role_path }}/files/usr/local/bin/weekly_reboot.sh"
    dest: "/usr/local/bin/weekly_reboot.sh"
    owner: "root"
    group: "root"
    mode: "0750"

- name: Copy weekly reboot cronjob to the server
  ansible.builtin.copy:
    src: "{{ role_path }}/files/etc/cron.d/weekly_reboot"
    dest: "/etc/cron.d/weekly_reboot"
    owner: "root"
    group: "root"
    mode: "0750"
