---
- name: Gather unique groups from vault data
  ansible.builtin.set_fact:
    common_user_groups_list: >-
      {{ common_new_users
        | map(attribute='groups')
        | join(',')
        | regex_replace('\s+', '')
        | split(',')
        | reject('equalto', '')
        | unique
        | list }}

- name: Ensure groups exist
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ common_user_groups_list }}"
  when: common_user_groups_list | length > 0

- name: Ensure user exists
  ansible.builtin.user:
    name: "{{ item.name }}"
    create_home: true
    shell: /bin/bash
    password: "{{ item.pass_hash if item.pass_hash | length > 0 else omit }}"
    password_lock: "{{ true if (item.pass_hash | length) == 0 else omit }}"
    groups: "{{ item.groups }}"
    append: true
    state: present
    update_password: on_create
  loop: "{{ common_new_users }}"
  loop_control:
    label: "{{ item.name }}"
  # no_log: true

- name: Add SSH key if provided
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_pubkey }}"
    state: present
  when: item.ssh_pubkey | length > 0
  loop: "{{ common_new_users }}"
  loop_control:
    label: "{{ item.name }}"

- name: Remove specified users
  ansible.builtin.user:
    name: "{{ item }}"
    remove: true
    state: absent
  loop: "{{ common_remove_users }}"
  loop_control:
    label: "{{ item }}"
