---
- name: Deploy SSH configuration from template
  ansible.builtin.template:
    src: "{{ role_path }}/templates/sshd_override.conf.j2"
    dest: "/etc/ssh/sshd_config.d/10-ansible.conf"
    owner: root
    group: root
    mode: "0640"
  notify:
    - Restart SSH service
