- name: Install UFW firewall
  ansible.builtin.package:
    name: "ufw"
    state: present

- name: Deny incoming traffic
  community.general.ufw:
    direction: incoming
    policy: deny
  notify:
    - Reload UFW rules

- name: Allow SSH (:{{ common_ssh_port }}) connection from whitelisted IPs
  community.general.ufw:
    rule: allow
    port: "{{ common_ssh_port }}"
    proto: tcp
    from_ip: "{{ item }}"
    comment: "SSH:{{ item }}"
  loop: "{{ common_whitelist_ips }}"
  notify:
    - Reload UFW rules

- name: Enable UFW firewall
  community.general.ufw:
    state: enabled
  notify:
    - Restart UFW service
