- name: Include update task
  ansible.builtin.include_tasks: 00_update.yml

- name: Include configuration task
  ansible.builtin.include_tasks: 01_configure.yml

- name: Include configuration task
  ansible.builtin.include_tasks: 02_swap.yml

- name: Include user creating task
  ansible.builtin.include_tasks: 10_users.yml

- name: Include SSH configuration task
  ansible.builtin.include_tasks: 20_ssh.yml
