- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: "{{ docker_ubuntu_gpg_url }}"
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: "{{ docker_ubuntu_repo_url }}"
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install Docker
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 86400
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Copy Docker configuration
  ansible.builtin.copy:
    src: "{{ role_path }}/files/daemon.json"
    dest: "/etc/docker/daemon.json"
    owner: "root"
    group: "docker"
    backup: true
    mode: "0640"
  notify:
    - Restart Docker service
