- name: Add docker permissions
  ansible.builtin.user:
    name: "{{ item.key }}"
    append: true
    groups: "docker"
    state: present
  with_dict: "{{ vault_admin_users }}"
  when: (vault_admin_users is defined) and  (vault_admin_users | length > 0)
