- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: "{{ docker_ubuntu_gpg_url }}"
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: "{{ docker_ubuntu_repo_url }}"
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install Docker
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 86400
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  when: ansible_distribution in ['Ubuntu']

- name: Copy Docker configuration
  ansible.builtin.copy:
    src: "{{ role_path }}/files/daemon.json"
    dest: "/etc/docker/daemon.json"
    owner: "root"
    group: "docker"
    backup: true
    mode: "0640"
  notify:
    - Restart Docker service

# TODO: Fix adding users to docker group
- name: Add users to docker group
  ansible.builtin.user:
    name: "{{ item.key }}"
    append: true
    groups: "docker"
    state: present
  loop: "{{ vault_admin_users }}"
  when: (vault_admin_users is defined) and  (vault_admin_users | length > 0)

- name: Check if UFW is installed
  check_mode: true
  ansible.builtin.package:
    name: "ufw"
    state: "present"
  register: ufw_check

- name: Check if UFW is enabled
  check_mode: true
  community.general.ufw:
    state: "enabled"
  register: ufw_enabled_check

- name: Append ufw-docker rules to /etc/ufw/after.rules
  ansible.builtin.blockinfile:
    path: "/etc/ufw/after.rules"
    block: "{{ lookup('file', '{{ role_path }}/templates/ufw-docker.rules.j2') }}"
    insertbefore: EOF
  when: not ufw_check.changed
  notify:
    - Restart UFW service
