---
- name: Bootstrap Ansible environment
  hosts: all
  become: true
  roles:
    - prepare
  vars:
    ansible_python_interpreter: "/usr/bin/python3"

- name: Configure the server
  hosts: all
  become: true
  roles:
    - common
    # - docker
    # - zabbix_agent
  vars:
    ansible_python_interpreter: "/root/.venv_ansible/bin/python3"

# FIXME: Use new user and port
- name: Reboot the server
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: "/root/.venv_ansible/bin/python3"
  tasks:
    - name: Update connection
      ansible.builtin.set_fact:
        ansible_user: "ansible"
        ansible_port: "{{ vault_ssh_port }}"

    - name: Reconnect with new settings
      ansible.builtin.meta: reset_connection

    - name: Reboot
      ansible.builtin.reboot:
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 10
