---
- name: Configure the server
  hosts: all
  become: true
  roles:
    - common
    - docker
    - clamav
    # - zabbix_agent
  vars:
    ansible_user: "ansible"
    ansible_port: "{{ vault_ssh_port }}"
    ansible_python_interpreter: "/root/.venv_ansible/bin/python3"
  tasks:
    - name: Reset connection
      ansible.builtin.meta: reset_connection

    - name: Reboot the system
      ansible.builtin.reboot:
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 10
