- name: Bootstrap Ansible environment
  hosts: all
  roles:
    - prepare
  become: true

- name: General deploy
  hosts: all
  roles:
    - common
    - docker
    - zabbix_agent
  become: true
  vars:
    ansible_python_interpreter: "/root/.venv_ansible/bin/python3"
